name: Getting Started Demo

on: push
jobs:
  Run image:
    name: Build
    runs-on: amazonlinux:2
    container:
       image: anutkarudeha/petclinic_app_build:v2
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Mkdir
        run: mkrir ./Demo2/artifact

      - name: Run script
        run: ./Demo2/scripts/test.sh
        
       
