name: Getting Started Demo

on:
  [workflow_dispatch]
  
jobs:
  run_image:
    name: Run image
    runs-on: ubuntu-latest
    container:
       image: anutkarudeha/petclinic_app_build:v3
    steps:
      - name: Fix Checkout
        run: |
          ldd --version

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Run the Docker image 
        run: |
          pwd
          ls
          export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          ./mvnw package

          ls ${{ github.workspace }}
          cp target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar ${{ github.workspace }}/artifact

#  docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

