name: Getting Started Demo

on:
  [workflow_dispatch]
  
jobs:
  run_image:
    name: Run image
    runs-on: ubuntu-latest
    container:
       image: anutkarudeha/petclinic_app_build:v2
    steps:
      - name: Run the Docker image 
        run: |
          pwd
          cd /__w/Demo2/Demo2/artifact
          chmod +x mvnw
          export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          ./mvnw package

#  docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

