name: Getting Started Demo

on:
  [workflow_dispatch]

defaults:
  run:
    shell: bash
  
jobs:
  run_image:
    name: Build
    runs-on: ubuntu-latest
    container:
       image: anutkarudeha/petclinic_app_build:v2
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: build jar 
        run: |
             mkrir ./.github/artifact
             cd /
             mkdir build_java_project

             cd build_java_project
             chmod +x mvnw
             export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
             ./mvnw package

             cp /build_java_project/target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar /artifact
        
       
