name: Getting Started Demo

on:
  [workflow_dispatch]
  
jobs:
  run_image:
    name: Run image
    runs-on: ubuntu-latest
    container:
       image: anutkarudeha/petclinic_app_build:v3
    steps:
      - name: Fix Checkout
        run: |
          ldd --version

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Run the Docker image 
        run: |
          pwd
          ls
          export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          ./mvnw package

          pwd
          ls -la
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar ${{ github.workspace }}/artifact

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact

  create_image:
    name: Create Image
    runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: my-artifact
            path: path/to/artifact
        - run: ls path/to/artifact

#  docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

